apiVersion: v1
kind: Service
metadata:
  name: example-nginx
  labels:
    app: example
    component: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: example
    component: nginx